name: Connect to GitHub Actions with tmate and run make menuconfig

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  tmate-session:
    runs-on: ubuntu-latest  # 使用 Ubuntu 运行器

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码到工作目录

      - name: Install tmate
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate  # 安装 tmate

      - name: Install necessary build tools
        run: |
          sudo apt-get install -y build-essential ncurses-dev  # 安装编译所需的工具和库

      - name: Start tmate session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "SSH connection string:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "Web connection string:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'

      - name: Wait for user to complete make menuconfig
        run: |
          echo "Waiting for you to complete make menuconfig in the tmate session..."
          sleep 3600  # 等待 1 小时，可根据需要调整时间

      - name: Optional: Continue with compilation
        run: |
          make  # 假设编译命令为 make，可根据实际情况修改
